name: Auto Keep Alive

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  empty_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git user information
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Make an empty commit
      run: git commit --allow-empty -m "Auto Keep Alive - empty commit"

    - name: Push empty commit to main branch
      run: git push origin HEAD
